# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitspork < Formula
  desc "When a fork just ain't good enough — a tool for managing upstream/downstream git repo relationships"
  homepage "https://github.com/rockholla/gitspork"
  version "1.0.0-rc07"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc07/gitspork_Darwin_x86_64.tar.gz"
      sha256 "402d55d41558ba14ef9de9d31e3878efd90e14a9b09578df0229fdf113d64cbe"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc07/gitspork_Darwin_arm64.tar.gz"
      sha256 "1ebf9f98007c3f1c73326b2b5cb19ba1ef724b57bba47ffa457d16cd98facc2f"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc07/gitspork_Linux_x86_64.tar.gz"
      sha256 "88a9a56d35d84a4bd69a6e2214cab33cb33b9c969f5fcdd1319793da8ff55390"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc07/gitspork_Linux_armv6.tar.gz"
      sha256 "680cc361e1367bb0d3835c8ba4a401c58ede319180755424cba740977b020767"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc07/gitspork_Linux_arm64.tar.gz"
      sha256 "727acdea31c5faa3b75f440b857ea5d6e9c5bd9e5b69587ad0164da134642a01"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  test do
    system "#{bin}/gitspork", "--version"
  end
end
