# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitspork < Formula
  desc "When a fork just ain't good enough — a tool for managing upstream/downstream git repo relationships"
  homepage "https://github.com/rockholla/gitspork"
  version "1.0.0-rc02"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc02/gitspork_Darwin_x86_64.tar.gz"
      sha256 "05e6bdbe5f125a6e4d38f611de1b2290bdf989ce715cf85bede1f4e47c69ee46"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc02/gitspork_Darwin_arm64.tar.gz"
      sha256 "d9ecf742a43646dc4fa5973582abb41f0c097dfdbf2b4a8fd0db8c61a32d93e7"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc02/gitspork_Linux_x86_64.tar.gz"
      sha256 "9422bbd8c9ea3c6fae3f2cc1ac2009ccad55c65b447f48dd9480eda2d2be6a3a"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc02/gitspork_Linux_armv6.tar.gz"
      sha256 "141277d7b8954d8c236434a76dbb9b1aa59391c488a2763957203333f1780312"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.0.0-rc02/gitspork_Linux_arm64.tar.gz"
      sha256 "efb15ca7b0dfbad2ffa9a7e235c8035e7c40209a4839ac105dde821ccc129be6"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  test do
    system "#{bin}/gitspork", "--version"
  end
end
