# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitspork < Formula
  desc "When a fork just ain't good enough — a tool for managing upstream/downstream git repo relationships"
  homepage "https://github.com/rockholla/gitspork"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.2/gitspork_Darwin_x86_64.tar.gz"
      sha256 "3dd0682927695cf71904ca41cab05b0cff14ab567425decc94797c9afe8d0d29"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.2/gitspork_Darwin_arm64.tar.gz"
      sha256 "5bd2b033a6951bd7b6303ebef1a9a3c456579a670796ccd0a3b36d71f8b12ae2"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.2/gitspork_Linux_x86_64.tar.gz"
      sha256 "991b7f3f3d8e181b756b860b5c4deb5d1ad8319c4f1f094d2825feac549d271d"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.2/gitspork_Linux_armv6.tar.gz"
      sha256 "632ab19af67b2df10262b15ef34cf5a570d956cdb04f8fb9996450e2ca88d6eb"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.2/gitspork_Linux_arm64.tar.gz"
      sha256 "0792d6fc19d2eee3c3bfb1a4aa20c7613a634e7bb2838e404691916836bb05aa"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  test do
    system "#{bin}/gitspork", "--version"
  end
end
