# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitspork < Formula
  desc "When a fork just ain't good enough — a tool for managing upstream/downstream git repo relationships"
  homepage "https://github.com/rockholla/gitspork"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.1/gitspork_Darwin_x86_64.tar.gz"
      sha256 "e9598fee6d197e4f756caaa63416aa507d82a2ff46f2da89aeab469be852bc81"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.1/gitspork_Darwin_arm64.tar.gz"
      sha256 "cfa5f499c7b4e364b2e5dd7ac2dda73e25093e7f99591fa91fd42162eee63015"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.1/gitspork_Linux_x86_64.tar.gz"
      sha256 "3b5297300f6f3892914676f25c66ad711dab65cfd1b188bd9bfb2c34d7434909"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.1/gitspork_Linux_armv6.tar.gz"
      sha256 "ee3cf72f6c35b649bae8e0d61c6ec259d45ee410cb577a66c40398c5ffb41360"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v1.1.1/gitspork_Linux_arm64.tar.gz"
      sha256 "ff37e934ec034c28344faa11bb206cfc2bf3d714cf7488bae97fdd9224ddeb96"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  test do
    system "#{bin}/gitspork", "--version"
  end
end
