# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitspork < Formula
  desc "When a fork just ain't good enough — a tool for managing upstream/downstream git repo relationships"
  homepage "https://github.com/rockholla/gitspork"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rockholla/gitspork/releases/download/v2.3.0/gitspork_Darwin_x86_64.tar.gz"
      sha256 "d1ac606bd26467708125e627e5c4e7922618bb3617d4c367b09bfb77abc17371"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rockholla/gitspork/releases/download/v2.3.0/gitspork_Darwin_arm64.tar.gz"
      sha256 "20f2b90caaf54c2cc60963847bd5fcef0fd7d44ceeef421b859c1225b61a9f9d"

      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v2.3.0/gitspork_Linux_x86_64.tar.gz"
      sha256 "50ac936b4f8913455d54a619b63c2e9d0b939ab09d9a626f85bb247b3c319bb1"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v2.3.0/gitspork_Linux_armv6.tar.gz"
      sha256 "962523a019d5d80c2665bdee6cd2751bbbb6cd4698cd2fd95063c687b467f9f1"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockholla/gitspork/releases/download/v2.3.0/gitspork_Linux_arm64.tar.gz"
      sha256 "4fbc9adcd62630753860ee2b29d001e17cbf01c3c6dff73820140046a02ff114"
      define_method(:install) do
        bin.install "gitspork"
      end
    end
  end

  test do
    system "#{bin}/gitspork", "--version"
  end
end
